test_num = 0
println("Началось тестирование Statistics:")
println("Производиться тестированание блока Variance")
include("Variance.jl")
println("")
println("Производиться тестированание блока Standart deviation")
include("Standart deviation.jl")
println("")
println("Производиться тестированание блока Sort")
include("Sort.jl")
println("")
println("Производиться тестированание блока RMS")
include("RMS.jl")
println("")
println("Производиться тестированание блока Power meter")
include("Power meter.jl")
println("")
println("Производиться тестированание блока Moving variance")
include("Moving_variance.jl")
println("")
println("Производиться тестированание блока Moving standart deviation")
include("Moving_standart_deviation.jl")
println("")
println("Производиться тестированание блока Moving RMS")
include("Moving_RMS.jl")
println("")
println("Производиться тестированание блока Moving minimum")
include("Moving_minimum.jl")
println("")
println("Производиться тестированание блока Moving maximum")
include("Moving_maximum.jl")
println("")
println("Производиться тестированание блока Moving average")
include("Moving_average.jl")
println("")
println("Производиться тестированание блока Minimum")
include("Minimum.jl")
println("")
println("Производиться тестированание блока Median filter")
include("Median_filter.jl")
println("")
println("Производиться тестированание блока Median")
include("Median.jl")
println("")
println("Производиться тестированание блока Mean")
include("Mean.jl")
println("")
println("Производиться тестированание блока Maximum")
include("Maximum.jl")
println("")
println("Производиться тестированание блока Detrend")
include("Detrend.jl")
println("")
using Printf
@printf "%s тестов пройдено" test_num
println("")
println("Тестирование Statistics завершено успешно")
