println("Производиться тестированание блока Variance")
include("Variance.jl")
println("")
println("Производиться тестированание блока Standart deviation")
include("Standart deviation.jl")
println("")
println("Производиться тестированание блока Sort")
include("Sort.jl")
println("")
println("Производиться тестированание блока RMS")
include("RMS.jl")
println("")
println("Производиться тестированание блока Power meter")
include("Power meter.jl")
println("")
println("Производиться тестированание блока Moving_variance")
include("Moving_variance.jl")